max_connections = [
    'test', [
            ['core', 600],
            ['doc', 400],
            ['enforcement', 800],
            ['eobu', 400],
            ['obu', 400],
            ['payment', 400],
            ['settlement', 400],
    'sb', [
            ['core', 600],
            ['doc', 600],
            ['enforcement', 600],
            ['eobu', 600],
            ['obu', 600],
            ['payment', 600],
            ['settlement', 600],
    'sb', [
            ['core', 600],
            ['doc', 600],
            ['enforcement', 600],
            ['eobu', 600],
            ['obu', 600],
            ['payment', 600],
            ['settlement', 600],
    'sb', [
            ['core', 600],
            ['doc', 600],
            ['enforcement', 600],
            ['eobu', 600],
            ['obu', 600],
            ['payment', 600],
            ['settlement', 600],
    ]