--liquibase formatted sql

--changeset bertalan.pasztor:0022
--comment AKP-602 stage_xtx_mass_and_axle_spacing_data tábla_létrehozása

CREATE TABLE ${schema_name}.stage_xtx_mass_and_axle_spacing_data (
   xtx_mass_and_axle_spacing_data_id varchar,
   md_load_header_id varchar,
   md_insert_ts timestamp(6),
   data_line_identifier varchar,
   edit_code varchar,
   departure  timestamp(6),
   logical_lane_number varchar,   
   physical_lane_number varchar,
   direction_code integer,
   speed integer,
   length integer,
   chassis_height_code integer,
   tag_code integer,
   failure_code integer,
   vehicle_class_code integer,
   axle_pattern_code integer,
   number_of_axles integer,
   axle_spacing_1 integer,
   axle_spacing_2 integer,
   axle_spacing_3 integer,
   axle_spacing_4 integer,
   axle_spacing_5 integer,
   axle_spacing_6 integer,
   axle_spacing_7 integer,
   axle_spacing_8 integer,
   axle_spacing_9 integer,
   axle_spacing_10 integer,
   axle_spacing_11 integer,
   axle_spacing_12 integer,
   axle_spacing_13 integer,
   axle_spacing_14 integer,
   axle_spacing_15 integer,
   axle_spacing_16 integer,
   axle_spacing_17 integer,
   axle_spacing_18 integer,
   axle_spacing_19 integer,
   axle_spacing_20 integer,
   axle_weight_1 integer,
   axle_weight_2 integer,
   axle_weight_3 integer,
   axle_weight_4 integer,
   axle_weight_5 integer,
   axle_weight_6 integer,
   axle_weight_7 integer,
   axle_weight_8 integer,
   axle_weight_9 integer,
   axle_weight_10 integer,
   axle_weight_11 integer,
   axle_weight_12 integer,
   axle_weight_13 integer,
   axle_weight_14 integer,
   axle_weight_15 integer,
   axle_weight_16 integer,
   axle_weight_17 integer,
   axle_weight_18 integer,
   axle_weight_19 integer,
   axle_weight_20 integer,
   sensor_temperature integer
);

-- lakehouse.prototype_landing.xtx_sensor_description_header definition


